AWSTemplateFormatVersion: '2010-09-09'
Description: "Media Insights Engine - Workflow to run VOD transcribe and translate application"

Parameters:

  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the Media Insights custom resource that handles creating operations, stages and workflows"
  OperatorLibraryStack:
    Description: "Name of the operator library stack"
    Type: String

Resources:
  # Stages

  MediaconvertStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "MediaconvertStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Mediaconvert"
  TranscribeStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "TranscribeStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Transcribe"
  WebCaptionsStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "WebCaptionsStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:WebCaptions"
  TranslateStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "TTranslateStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Translate"
  TranslateBatchStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "TranslateBatchStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:TranslateWebCaptions"
  CaptionFileStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "CaptionFileStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:WebToSRTCaptions"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:WebToVTTCaptions"
  

  # Workflow

  TranslatorWorkflow:
    DependsOn:
      - MediaconvertStage
      - TranscribeStage
      - WebCaptionsStage
      - TranslateBatchStage
      - CaptionFileStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: "TranslatorWorkflow"
      StartAt: !GetAtt MediaconvertStage.Name
      Stages: !Sub
        - |-
          {
            "${MediaconvertStage}":{
              "Next": "${TranscribeStage}"
              },
            "${TranscribeStage}":{
              "Next": "${WebCaptionsStage}"
              },
            "${WebCaptionsStage}":{
              "Next": "${TranslateBatchStage}"
              },
            "${TranslateBatchStage}":{
              "Next": "${CaptionFileStage}"
              },
            "${CaptionFileStage}":{
              "End": true
              }
          }
        - {
          MediaconvertStage: !GetAtt MediaconvertStage.Name,
          TranscribeStage: !GetAtt TranscribeStage.Name,
          WebCaptionsStage: !GetAtt WebCaptionsStage.Name,
          TranslateBatchStage: !GetAtt TranslateBatchStage.Name,
          CaptionFileStage: !GetAtt CaptionFileStage.Name
        }