service: aws-captions-node-sdk-layer

provider:
  name: aws
  profile: transcribe
  region: us-west-2
  stage: prod

custom:
    stage: '${opt:stage, self:provider.stage}'

layers:
  aws-captions-node-sdk-layer:
    path: package
    name: ${self:custom.stage}-${self:service}
    description: 'Recent Node.js 8.10 AWS Node SDK'
    compatibleRuntimes:
      - nodejs12.x
    licenseInfo: 'Apache-2.0'
    # allowedAccounts:
    #   - !Join [ '', [ !Ref AWS::AccountId ]]
