name: test-scheduled-workflow

on:
  workflow_dispatch:
    inputs:
        note:
          description: 'Note'
          required: false

jobs:
  # Build and new deploy based on latest release of MIE
  build-content-localization-dev-us-west-2:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out development branch
        uses: actions/checkout@v2.3.4
        with:
          ref: development

      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Generate short sha
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Run build script
        uses: chrislennon/action-aws-cli@v1.1
        run: |
          cd deployment
          CONTENT_LOCALIZATION_STACK_NAME=cl-dev
          EMAIL=micontentlocalization@gmail.com
          REGION=us-west-2
          VERSION=${SHORT_SHA}
          DIST_OUTPUT_BUCKET=micl-dev
          TEMPLATE_OUTPUT_BUCKET=$DIST_OUTPUT_BUCKET-$REGION
          ./build.sh $DIST_OUTPUT_BUCKET-$REGION $VERSION $REGION
          echo "read in the template"
          read -r TEMPLATE < ../src/templateUrlMieRelease.txt

      - name: 'Upload One-click Deployment Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: templateUrlMieRelease
          path: src/templateUrlMieRelease.txt
          retention-days: 3
      - name: 'Upload Developer Deployment Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: templateUrlMieDevelopment
          path: src/templateUrlMieDevelopment.txt
          retention-days: 3

  build-mie-dev-us-west-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MIE development branch
        uses: actions/checkout@v2
        with:
          repository: awslabs/aws-media-insights-engine
          ref: development

      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Generate short sha
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Run build script
        uses: chrislennon/action-aws-cli@v1.1
        run: |
          aws --version
          account_id=$(aws sts get-caller-identity --query Account --output text)
          echo $account_id
          if [ $? -ne 0 ]; then
            msg "ERROR: Failed to get AWS account ID"
            die 1
          fi
          # Validate ownership of $global_dist_dir
          aws s3api head-bucket --bucket $TEMPLATE_OUTPUT_BUCKET --expected-bucket-owner $account_id
          if [ $? -ne 0 ]; then
            msg "ERROR: Your AWS account does not own s3://$DIST_OUTPUT_BUCKET"
            die 1
          fi
          cd deployment
          MIE_STACK_NAME="mie-dev"
          REGION=us-west-2
          VERSION=${SHORT_SHA}
          DIST_OUTPUT_BUCKET=micl-dev
          TEMPLATE_OUTPUT_BUCKET=micl-dev-us-west-2
          ./build-s3-dist.sh --no-layer --template-bucket $TEMPLATE_OUTPUT_BUCKET --code-bucket $DIST_OUTPUT_BUCKET --version $VERSION --region $REGION
          read -r TEMPLATE < templateUrl.txt

      - name: 'Upload MIE One-click Deployment Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: templateUrl
          path: deployment/templateUrl.txt
          retention-days: 3
      
      
